version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"  # Expose MongoDB on port 27017
    volumes:
      - mongo-data:/data/db  # Persist MongoDB data in a named volume

  esp8266-backend:
    build:
      context: .
    container_name: esp8266-backend
    ports:
      - "3000:3000"  # Expose your Node.js app on port 3000
    environment:
      MONGO_URL: mongodb://mongodb:27017/animal-feeding  # MongoDB connection string
    depends_on:
      - mongodb  # Make sure MongoDB starts before Node.js app

volumes:
  mongo-data:  # Named volume to persist MongoDB data
