version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - backend-network

  esp8266-backend:
    build:
      context: .
    container_name: esp8266-backend
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongodb:27017/animal-feeding
    depends_on:
      - mongodb
    networks:
      - backend-network

networks:
  backend-network:

volumes:
  mongo-data:
